# Generated by Django 5.0.1 on 2024-01-05 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_apps', '0003_remove_incidents_incident_id_incidents_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidents',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='incident_apps.handler'),
        ),
        migrations.AlterField(
            model_name='incidents',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
